### ISSUE TITLE
Please DO NOT change the provided database name to "flutter_$name.db"

### ISSUE THREAD

**Issue by Dinosane2** [hsul4n/dart-sqfly#1]
1) why?
2) the whole init() method is not overridable as it uses lot of private vars
3) once the name is provided, please keep it
4) path could be an optional parameter as well

I´m trying to use sqfly into a flutter module to new features of a big old Android Java app. So I need to open  and existent sqlite database file. Change the old project to "flutter_gestor.db" is not an option for several reasons.

**Comment by hsul4n** [comment]
@Dinosane2 Will check that, as you mentioned above the path will be provided as optional params and the default will be exists..

**Comment by hsul4n** [comment]
@Dinosane2, fixed https://github.com/hsul4n/dart-sqfly/commit/15cec41f084a416561df9ce8ba91a393b4ffca84

**Comment by Dinosane2** [comment]
Thanks again for your nice work!
